# Generated by Django 5.0 on 2023-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('RoleCode', models.CharField(max_length=50)),
                ('RoleName', models.CharField(max_length=50)),
                ('RoleDescription', models.CharField(max_length=200)),
                ('isActive', models.BooleanField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
