# Generated by Django 5.0 on 2023-12-13 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_remove_contractorworkprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractorWorkProfiles',
            fields=[
                ('contractorWorkProfileId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=True)),
                ('contractorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
                ('documentMappingId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.documentmapping')),
                ('expertiseId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.expertise')),
                ('jobTypeId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.jobtype')),
            ],
        ),
    ]
