# Generated by Django 4.2.7 on 2023-12-14 07:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_contractorworkprofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('searchId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('searchCommand', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('searchStartedOn', models.CharField(blank=True, max_length=100)),
                ('searchEndedOn', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workOrder',
            fields=[
                ('workOrderId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('estimatedAmount', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('estimatedStartDate', models.CharField(blank=True, max_length=100)),
                ('estimatedEndDate', models.CharField(blank=True, max_length=100)),
                ('isAssigned', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('addressId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.address')),
                ('documentMappingID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.documentmapping')),
                ('expertiseId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.expertise')),
                ('jobTypeId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='workOrderProgress',
            fields=[
                ('workOrderProgressId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('actionedOn', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('completedPercentage', models.CharField(blank=True, max_length=50)),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='workOrderInvoice',
            fields=[
                ('workOrderInvoiceId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('totalAmount', models.CharField(blank=True, max_length=50)),
                ('invoiveJson', models.CharField(blank=True, max_length=500)),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='workOrderContractorPreference',
            fields=[
                ('workOrderContractorPreferenceId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ContractorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='workOrderAssigment',
            fields=[
                ('workOrderAssigmentId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('requestStatus', models.CharField(blank=True, max_length=100)),
                ('responseStatus', models.CharField(blank=True, max_length=100)),
                ('contractorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='serviceRequest',
            fields=[
                ('serviceRequestId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('discription', models.CharField(blank=True, max_length=50)),
                ('userId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='searchResult',
            fields=[
                ('serviceRequestId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('contractorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
                ('searchId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.search')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='workOrderId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder'),
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('reviewId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('entityId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
                ('entityType', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.role')),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='contractorWorkProfileRequest',
            fields=[
                ('contractorWorkProfileRequestId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('contractorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.user')),
            ],
        ),
    ]
