# Generated by Django 4.2.7 on 2023-12-14 07:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_search_workorder_workorderprogress_workorderinvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('actionedOn', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_messages', to='role.user')),
                ('documentId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.document')),
                ('userId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='role.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderMessage',
            fields=[
                ('workOrderMessageId', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('messageId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.message')),
                ('workOrderId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder')),
            ],
        ),
    ]
