# Generated by Django 5.0 on 2023-12-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_message_workordermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
