# Generated by Django 4.2.7 on 2023-12-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_alter_document_documenttypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmapping',
            name='documentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.document'),
        ),
        migrations.AlterField(
            model_name='documentmapping',
            name='entityId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.user'),
        ),
        migrations.AlterField(
            model_name='documentmapping',
            name='entityType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
