# Generated by Django 4.2.7 on 2024-01-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0010_delete_contractorworkprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='workOrderId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='workorderprogress',
            old_name='workOrderId',
            new_name='workOworkOrderrderId',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
