# Generated by Django 5.0 on 2024-03-03 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0011_rename_workorderid_workorder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='workOrder2',
            fields=[
                ('Id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('estimatedAmount', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('estimatedStartDate', models.CharField(blank=True, max_length=100, null=True)),
                ('estimatedEndDate', models.CharField(blank=True, max_length=100, null=True)),
                ('isAssigned', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('addressId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.address')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.document')),
                ('expertiseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.expertise')),
                ('jobTypeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.jobtype')),
            ],
        ),
    ]
