# Generated by Django 5.0 on 2024-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0012_workorder2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
    ]
