# Generated by Django 5.0 on 2024-03-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0014_workorder2_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='workOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='role.workorder2'),
        ),
    ]
