# Generated by Django 5.0 on 2024-03-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0015_message_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderassigment',
            name='workOrderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.workorder2'),
        ),
    ]
