# Generated by Django 5.0 on 2024-03-06 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0019_alter_message_time2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
