# Generated by Django 5.0 on 2024-04-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0021_alter_review_workorderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorworkprofiles',
            name='documentMappingId',
        ),
        migrations.AddField(
            model_name='contractorworkprofiles',
            name='documentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.document'),
        ),
    ]
